Add registry url, username and password arguments (#44)
* Added new arguments for registry url, username and password

* Modified description

* Added step to log in to container registry using registry url, username and password

* Addressed CR comments

* Addressed CR comments

* Replaced ACR with Container Registry

* Addressed CR comments

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -21,6 +21,15 @@ inputs:
       'The password used to authenticate push requests to the provided Azure Container Registry. If not provided, an
       access token will be generated via "az acr login" and provided to "docker login" to authenticate the requests.'
     required: false
+  registryUrl:
+    description: 'The base URL of the Container Registry that the runnable application image will be pushed to.'  
+    required: false
+  registryUsername: 
+    description: 'The username used to authenticate push requests to the provided Container Registry using the "docker login" action.'  
+    required: false
+  registryPassword: 
+    description: 'The password used to authenticate push requests to the provided Container Registry using the "docker login" action.'  
+    required: false
   azureCredentials:
     description: |
       'Azure credentials used by the `azure/login` action to authenticate Azure CLI requests if the user has not
@@ -28,21 +37,21 @@ inputs:
     required: false
   imageToBuild:
     description: |
-      'The custom name of the image that is to be built, pushed to ACR and deployed to the Container App by this action.
-      Note: this image name should include the ACR server; e.g., <acr-name>.azurecr.io/<repo>:<tag>. If this argument is
+      'The custom name of the image that is to be built, pushed to the Container Registry and deployed to the Container App by this action.
+      Note: this image name should include the registry server; e.g., <registryUrl>/<repo>:<tag>. If this argument is
       not provided, a default image name will be constructed in the form of
       <acr-name>.azurecr.io/github-action/container-app:<github-run-id>.<github-run-attempt>.'
     required: false
   imageToDeploy:
     description: |
-      'The custom name of an image that has already been pushed to ACR and will be deployed to the Container App by this
-      action. Note: this image name should include the ACR server; e.g., <acr-name>.azurecr.io/<repo>:<tag>. If this
+      'The custom name of an image that has already been pushed to the Container Registry and will be deployed to the Container App by this
+      action. Note: this image name should include the registry server; e.g., <registryUrl>/<repo>:<tag>. If this
       argument is not provided, the value provided (or determined) for the "imageToBuild" argument will be used.'
     required: false
   dockerfilePath:
     description: |
       'Relative path to the Dockerfile in the provided application source that should be used to build the image that is
-      then pushed to ACR and deployed to the Container App. If not provided, this action will check if there is a file
+      then pushed to the Container Registry and deployed to the Container App. If not provided, this action will check if there is a file
       named "Dockerfile" in the provided application source and use that to build the image. Otherwise, the Oryx++
       Builder will be used to create the image.'
     required: false
@@ -128,11 +137,18 @@ runs:
         CA_GH_ACTION_RESULT_ARG="--property 'result=failed'"
         echo "CA_GH_ACTION_RESULT_ARG=${CA_GH_ACTION_RESULT_ARG}" >> $GITHUB_ENV
 
-    - name: Check for ACR name provided with application source path
-      if: ${{ inputs.appSourcePath != '' && inputs.acrName == '' }}
+    - name: Check that an ACR name and a registry URL are not provided together
+      if: ${{ inputs.acrName != '' && inputs.registryUrl != '' }}
+      shell: bash
+      run: | 
+        echo "Both 'acrName' and 'registryUrl' arguments cannot be provided together."
+        exit 1    
+
+    - name: Check for ACR name or any other registry url provided with application source path
+      if: ${{ inputs.appSourcePath != '' && inputs.acrName == '' && inputs.registryUrl == '' }}
       shell: bash
       run: |
-        echo "The 'acrName' argument must also be provided if the 'appSourcePath' argument is provided."
+        echo "The 'acrName' argument or the 'registryUrl' argument must also be provided if the 'appSourcePath' argument is provided."
         exit 1
 
     - name: Check for application source path, a previously built image or a YAML configuration file
@@ -174,12 +190,39 @@ runs:
         username: ${{ inputs.acrUsername }}
         password: ${{ inputs.acrPassword }}
 
+    - name: Log in to Container Registry
+      uses: docker/login-action@v2.0.0
+      if: ${{ inputs.registryUrl != '' && inputs.registryUsername != '' && inputs.registryPassword != '' }}
+      with:
+        registry: ${{ inputs.registryUrl }}
+        username: ${{ inputs.registryUsername }}
+        password: ${{ inputs.registryPassword }}
+
+    - name: Export Container Registry information to environment variable 
+      if: ${{ inputs.registryUrl != '' && inputs.registryUsername != '' && inputs.registryPassword != '' && env.CA_GH_ACTION_ONLY_YAML != 'true' }}
+      shell: bash
+      run: |
+        CA_GH_ACTION_REGISTRY_LOGIN_ARG="--registry-server ${{ inputs.registryUrl }} --registry-username ${{ inputs.registryUsername }} --registry-password ${{ inputs.registryPassword }}"
+        CA_GH_ACTION_REGISTRY_URL=${{ inputs.registryUrl }}
+        CA_GH_ACTION_REGISTRY_USERNAME=${{ inputs.registryUsername }}
+        CA_GH_ACTION_REGISTRY_PASSWORD=${{ inputs.registryPassword }}
+        echo "CA_GH_ACTION_REGISTRY_LOGIN_ARG=${CA_GH_ACTION_REGISTRY_LOGIN_ARG}" >> $GITHUB_ENV
+        echo "CA_GH_ACTION_REGISTRY_URL=${CA_GH_ACTION_REGISTRY_URL}" >> $GITHUB_ENV
+        echo "CA_GH_ACTION_REGISTRY_USERNAME=${CA_GH_ACTION_REGISTRY_USERNAME}" >> $GITHUB_ENV
+        echo "CA_GH_ACTION_REGISTRY_PASSWORD=${CA_GH_ACTION_REGISTRY_PASSWORD}" >> $GITHUB_ENV
+
     - name: Export Azure Container Registry information to environment variable for Azure CLI command
       if: ${{ inputs.acrName != '' && inputs.acrUsername != '' && inputs.acrPassword != '' && env.CA_GH_ACTION_ONLY_YAML != 'true' }}
       shell: bash
       run: |
-        CA_GH_ACTION_ACR_LOGIN_ARG="--registry-server ${{ inputs.acrName }}.azurecr.io --registry-username ${{ inputs.acrUsername }} --registry-password ${{ inputs.acrPassword }}"
-        echo "CA_GH_ACTION_ACR_LOGIN_ARG=${CA_GH_ACTION_ACR_LOGIN_ARG}" >> $GITHUB_ENV
+        CA_GH_ACTION_REGISTRY_LOGIN_ARG="--registry-server ${{ inputs.acrName }}.azurecr.io --registry-username ${{ inputs.acrUsername }} --registry-password ${{ inputs.acrPassword }}"
+        CA_GH_ACTION_REGISTRY_URL=${{ inputs.acrName }}.azurecr.io
+        CA_GH_ACTION_REGISTRY_USERNAME=${{ inputs.acrUsername }}
+        CA_GH_ACTION_REGISTRY_PASSWORD=${{ inputs.acrPassword }}
+        echo "CA_GH_ACTION_REGISTRY_LOGIN_ARG=${CA_GH_ACTION_REGISTRY_LOGIN_ARG}" >> $GITHUB_ENV
+        echo "CA_GH_ACTION_REGISTRY_URL=${CA_GH_ACTION_REGISTRY_URL}" >> $GITHUB_ENV
+        echo "CA_GH_ACTION_REGISTRY_USERNAME=${CA_GH_ACTION_REGISTRY_USERNAME}" >> $GITHUB_ENV
+        echo "CA_GH_ACTION_REGISTRY_PASSWORD=${CA_GH_ACTION_REGISTRY_PASSWORD}" >> $GITHUB_ENV
 
     - name: Get access token to log in to Azure Container Registry
       if: ${{ inputs.acrName != '' && (inputs.acrUsername == '' || inputs.acrPassword == '') }}
@@ -188,6 +231,8 @@ runs:
         CA_GH_ACTION_ACR_ACCESS_TOKEN=$(az acr login --name ${{ inputs.acrName }} --output json --expose-token | jq -r '.accessToken')
         echo "CA_GH_ACTION_ACR_ACCESS_TOKEN=${CA_GH_ACTION_ACR_ACCESS_TOKEN}" >> $GITHUB_ENV
         docker login ${{ inputs.acrName }}.azurecr.io -u 00000000-0000-0000-0000-000000000000 -p $CA_GH_ACTION_ACR_ACCESS_TOKEN
+        CA_GH_ACTION_REGISTRY_URL=${{ inputs.acrName }}.azurecr.io
+        echo "CA_GH_ACTION_REGISTRY_URL=${CA_GH_ACTION_REGISTRY_URL}" >> $GITHUB_ENV
 
     - name: Export Dockerfile path to environment variable
       if: ${{ inputs.appSourcePath != '' && inputs.dockerfilePath != '' }}
@@ -211,11 +256,11 @@ runs:
         echo "CA_GH_ACTION_IMAGE_TO_BUILD=${CA_GH_ACTION_IMAGE_TO_BUILD}" >> $GITHUB_ENV
 
     - name: Determine name of image to build if not provided
-      if: ${{ inputs.acrName != '' && inputs.imageToBuild == '' && env.CA_GH_ACTION_ONLY_YAML != 'true' }}
+      if: ${{ env.CA_GH_ACTION_REGISTRY_URL != '' && inputs.imageToBuild == '' && env.CA_GH_ACTION_ONLY_YAML != 'true' }}
       shell: bash
       run: |
-        CA_GH_ACTION_IMAGE_TO_BUILD="${{ inputs.acrName }}.azurecr.io/github-action/container-app:${{ github.run_id }}.${{ github.run_attempt }}"
-        echo "CA_GH_ACTION_IMAGE_TO_BUILD=${CA_GH_ACTION_IMAGE_TO_BUILD}" >> $GITHUB_ENV
+        CA_GH_ACTION_IMAGE_TO_BUILD="${{ env.CA_GH_ACTION_REGISTRY_URL }}/github-action/container-app:${{ github.run_id }}.${{ github.run_attempt }}"
+        echo "CA_GH_ACTION_IMAGE_TO_BUILD=${CA_GH_ACTION_IMAGE_TO_BUILD}" >> $GITHUB_ENV    
 
     - name: Export name of image to deploy to environment variable
       if: ${{ inputs.imageToDeploy != '' }}
@@ -477,7 +522,7 @@ runs:
           --file ${{ env.CA_GH_ACTION_DOCKERFILE_PATH }} \
           ${{ inputs.appSourcePath }}
 
-    - name: Push image to Azure Container Registry
+    - name: Push image to Container Registry
       if: ${{ inputs.appSourcePath != '' }}
       shell: bash
       run: docker push ${{ env.CA_GH_ACTION_IMAGE_TO_DEPLOY }}
@@ -502,7 +547,7 @@ runs:
           --environment ${{ env.CA_GH_ACTION_CONTAINER_APP_ENVIRONMENT }} \
           ${{ env.CA_GH_ACTION_INGRESS_ARG }} \
           ${{ env.CA_GH_ACTION_TARGET_PORT_ARG }} \
-          ${{ env.CA_GH_ACTION_ACR_LOGIN_ARG }} \
+          ${{ env.CA_GH_ACTION_REGISTRY_LOGIN_ARG }} \
           ${{ env.CA_GH_ACTION_CONTAINER_APP_ENVIRONMENT_VARIABLES_ARG }}
 
     - name: Update the existing Container App from a YAML configuration file
@@ -522,15 +567,15 @@ runs:
         echo "CA_GH_ACTION_USE_UP=${CA_GH_ACTION_USE_UP}" >> $GITHUB_ENV
 
     - name: Update the Container Registry details on the existing Container App
-      if: ${{ env.CA_GH_ACTION_ACR_LOGIN_ARG != '' && env.CA_GH_ACTION_USE_UP != 'true' && env.CA_GH_ACTION_RESOURCE_EXISTS == 'true' && env.CA_GH_ACTION_YAML_PROVIDED != 'true' }}
+      if: ${{ env.CA_GH_ACTION_REGISTRY_LOGIN_ARG != '' && env.CA_GH_ACTION_USE_UP != 'true' && env.CA_GH_ACTION_RESOURCE_EXISTS == 'true' && env.CA_GH_ACTION_YAML_PROVIDED != 'true' }}
       shell: bash
       run: |
         az containerapp registry set \
           -g ${{ env.CA_GH_ACTION_RESOURCE_GROUP }} \
           -n ${{ inputs.containerAppName }} \
-          --server ${{ inputs.acrName }}.azurecr.io \
-          --username ${{ inputs.acrUsername }} \
-          --password ${{ inputs.acrPassword }}
+          --server ${{ env.CA_GH_ACTION_REGISTRY_URL }} \
+          --username ${{ env.CA_GH_ACTION_REGISTRY_USERNAME }} \
+          --password ${{ env.CA_GH_ACTION_REGISTRY_PASSWORD }}
 
     - name: Update the existing Container App from provided arguments via 'update' (no ingress values provided)
       if: ${{ env.CA_GH_ACTION_USE_UP != 'true' && env.CA_GH_ACTION_YAML_PROVIDED != 'true' && env.CA_GH_ACTION_RESOURCE_EXISTS == 'true' }}
@@ -567,7 +612,7 @@ runs:
           ${{ env.CA_GH_ACTION_TARGET_PORT_ARG }} \
           ${{ env.CA_GH_ACTION_INGRESS_ARG }} \
           ${{ env.CA_GH_ACTION_CONTAINER_APP_ENVIRONMENT_VARIABLES_ARG }} \
-          ${{ env.CA_GH_ACTION_ACR_LOGIN_ARG }}
+          ${{ env.CA_GH_ACTION_REGISTRY_LOGIN_ARG }}
 
     - name: Disable ingress on the existing Container App
       if: ${{ env.CA_GH_ACTION_RESOURCE_EXISTS == 'true' && inputs.ingress == 'disabled' && env.CA_GH_ACTION_YAML_PROVIDED != 'true' }}
